### PR TITLE
Update to ginkgo v2 + lager v3

### PR DESCRIPTION
**Pull request by geofffranks**
Various cloudfoundry components using this library are getting upgraded to code.cloudfoundry.org/lager/v3, and github.com/onsi/ginkgo/v2. We need to modify this at a minimum to handle lager/v3 to be able to keep testing with the library. 

**One change to note:** In ginkgo/v2, the table related functions, including `Entry()` were moved into the top level `github.com/onsi/ginkgo/v2` package, which conflicted with this package's `Entry()` function when both were imported to the local namespace.

I couldn't find any cases where we were using `Entry()` directly in our packages consuming this library, or the tests in this library. It seemed easiest to rename it to `LogEntry()` to preserve the local namespace imports, rather than needing to either prefix all ginkgo calls with `ginkgo.` or all glager calls with `glager.` Totally open to other suggestions if you'd prefer not to rename that function though.

### CODE REVIEW

**Comment by st3v** [comment]
Thanks for the PR, @geofffranks. How urgent do you need this merged? I'm currently traveling with no access to a computer other than my phone. Realistically, I won't be able to look at this before the end of April. Does that work for you?

**Comment by geofffranks** [comment]
That should be fine. We have our code redirected to the PR commit, in the mean time and will just need to update it back to the main branch once you have time to look.Enjoy your travels!Sent from my iPhoneOn Mar 30, 2023, at 11:52 AM, Stev Witzel ***@***.***> wrote:﻿
Thanks for the PR, @geofffranks. How urgent do you need this merged? I'm currently traveling with no access to a computer other than my phone. Realistically, I won't be able to look at this before the end of April. Does that work for you?

**Comment by winkingturtle-vmw** [comment]
@st3v Any chance you've reviewed this PR and can cut a release after that? We are running these changes off of a personal fork that we would ideally like to get off of.

**Comment by st3v** [comment]
Merged and available in [v0.4.0](https://github.com/st3v/glager/releases/tag/v0.4.0). Thanks again @geofffranks!

**Pull request merged**
